/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author DELL
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_TenNhom = new javax.swing.JLabel();
        btn_Register = new javax.swing.JButton();
        btn_Login = new javax.swing.JButton();
        lb_login = new javax.swing.JLabel();
        lb_register = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To My Shop");
        setMinimumSize(new java.awt.Dimension(1345, 845));
        setPreferredSize(new java.awt.Dimension(1329, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_TenNhom.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lb_TenNhom.setForeground(new java.awt.Color(255, 255, 51));
        lb_TenNhom.setText("   Nhóm 19 Barber");
        getContentPane().add(lb_TenNhom, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 506, 290, 40));

        btn_Register.setBackground(new java.awt.Color(153, 0, 0));
        btn_Register.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Register.setForeground(new java.awt.Color(255, 255, 51));
        btn_Register.setText("Register");
        btn_Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 242, 89)));
        getContentPane().add(btn_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 60, 150, 40));

        btn_Login.setBackground(new java.awt.Color(153, 0, 0));
        btn_Login.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 51));
        btn_Login.setText("Login");
        btn_Login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 242, 89)));
        getContentPane().add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 150, 40));

        lb_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/user.png"))); // NOI18N
        getContentPane().add(lb_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 30, 40));

        lb_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/register.png"))); // NOI18N
        getContentPane().add(lb_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 60, 30, 40));

        background.setForeground(new java.awt.Color(204, 204, 204));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/anh_nen_cat_toc.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_Register;
    private javax.swing.JLabel lb_TenNhom;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_register;
    // End of variables declaration//GEN-END:variables
}
//test
